import type { RssFeedConfig } from "../types";

export const RSS_FEEDS: RssFeedConfig[] = [
  {
    id: "ibm-quantum",
    name: "IBM Quantum Blog",
    url: "https://www.ibm.com/quantum/blog/rss.xml",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "google-quantum-ai",
    name: "Google Quantum AI",
    url: "https://blog.google/technology/research/feed/",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "quantinuum",
    name: "Quantinuum",
    url: "https://www.quantinuum.com/feed/",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "ionq",
    name: "IonQ",
    url: "https://ionq.com/blog/rss.xml",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "psiquantum",
    name: "PsiQuantum",
    url: "https://www.psiquantum.com/feed/",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "rigetti",
    name: "Rigetti",
    url: "https://www.rigetti.com/feed",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "xanadu",
    name: "Xanadu",
    url: "https://www.xanadu.ai/feed/",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "quantum-computing-report",
    name: "Quantum Computing Report",
    url: "https://quantumcomputingreport.com/feed/",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "quantum-insider",
    name: "The Quantum Insider",
    url: "https://thequantuminsider.com/feed/",
    category: "ECOSYSTEM",
    enabled: true,
  },
  {
    id: "quanta-magazine",
    name: "Quanta Magazine",
    url: "https://www.quantamagazine.org/feed/",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "nature-quantum",
    name: "Nature Quantum Information",
    url: "https://www.nature.com/natquantuminfo.rss",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "arxiv-quant-ph",
    name: "arXiv Quantum Physics",
    url: "http://export.arxiv.org/rss/quant-ph",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "mit-quantum",
    name: "MIT News Quantum",
    url: "https://news.mit.edu/topic/quantum-computing/feed",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "phys-org-quantum",
    name: "Phys.org Quantum Physics",
    url: "https://phys.org/rss-feed/physics-news/quantum-physics/",
    category: "RESEARCH",
    enabled: true,
  },
  {
    id: "ieee-spectrum-quantum",
    name: "IEEE Spectrum Quantum",
    url: "https://spectrum.ieee.org/feeds/topic/quantum-computing.rss",
    category: "HARDWARE",
    enabled: true,
  },
  {
    id: "iisc-news",
    name: "IISc News",
    url: "https://iisc.ac.in/wp-feed/",
    category: "INDIA",
    enabled: true,
  },
  {
    id: "dst-india",
    name: "DST India",
    url: "https://dst.gov.in/rss-feed",
    category: "INDIA",
    enabled: true,
  },
  {
    id: "qpiai",
    name: "QpiAI",
    url: "https://qpiai.tech/feed/",
    category: "INDIA",
    enabled: true,
  },
  {
    id: "qnulabs",
    name: "QNu Labs",
    url: "https://qnulabs.com/feed/",
    category: "INDIA",
    enabled: true,
  },
  {
    id: "bosonq-psi",
    name: "BosonQ Psi",
    url: "https://bosonqpsi.com/feed/",
    category: "INDIA",
    enabled: true,
  },
];

export function getEnabledFeeds(): RssFeedConfig[] {
  return RSS_FEEDS.filter((feed) => feed.enabled);
}
